config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources :homes
  resources :studios, only: [:index, :new, :create, :edit, :update]
  resources :songs
 
  get '/sound-designs' => 'sound_designs#index'
  get '/sound-designs/new' => 'sound_designs#new'
  post '/sound-designs' => 'sound_designs#create'
  get '/sound-designs/:id' => 'sound_designs#show', as: 'sound_design'
  get '/sound-designs/:id/edit' => 'sound_designs#edit', as: 'sound_design_edit'
  patch '/sound-designs/:id' => 'sound_designs#update'
  put '/sound-designs/:id' => 'sound_designs#update'
  delete '/sound-designs/:id' => 'sound_designs#destroy'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
  has_rich_text :main_description
  has_rich_text :sub_description
  has_one_attached :image
end

app/models/iframe.rb
class Iframe < ApplicationRecord
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  validates :title, presence: true,
                    length: { minimum: 2 }
  def previous
    Song.where(["id < ?", id]).last
  end

  def next
    Song.where(["id > ?", id]).first
  end

  has_many :iframes, dependent: :destroy

  accepts_nested_attributes_for :iframes, reject_if: :all_blank, allow_destroy: true
end

app/models/sound_design.rb
class SoundDesign < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  validates :title, presence: true,
                    length: { minimum: 2 }

  def previous
    SoundDesign.where(['id < ?', id]).last
  end

  def next
    SoundDesign.where(['id > ?', id]).first
  end

  has_many :vimeos, dependent: :destroy

  accepts_nested_attributes_for :vimeos, reject_if: :all_blank, allow_destroy: true
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_rich_text :main_description
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/vimeo.rb
class Vimeo < ApplicationRecord
  belongs_to :sound_design
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @homes = Home.all.order("created_at DESC")
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    @home.save
    redirect_to root_path
  end

  def show
    @home = Home.find(params[:id])
  end

  def edit
    @home = Home.find(params[:id])
  end

  def update
    @home = Home.find(params[:id])

    if @home.update(home_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
    def home_params
      params.require(:home).permit(:main_description, :sub_description, :image)
    end
end

app/controllers/iframe_controller.rb
class IframeController < ApplicationController
  def index
    
  end

  def show
    
  end

  def new
    
  end

  def edit
    
  end

  def create
    
  end

  def update
    
  end

  def destroy
    
  end

  private
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @songs = Song.all.order("created_at DESC")
  end
  
  def new
    @song = Song.new
    @song.iframes.build
  end

  def create
    @song = Song.new(song_params)

    @song.save
    redirect_to @song
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path
  end

  private
    def song_params
      params.require(:song).permit(:title, :description, :youtube_url, :soundcloud_url, :album_url, :image, iframes_attributes: [:id, :iframe_url, :_destroy])
    end
end

app/controllers/sound_designs_controller.rb
class SoundDesignsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @sound_designs = SoundDesign.all.order("created_at DESC")
  end

  def new
    @sound_design = SoundDesign.new
    @sound_design.vimeos.build
  end

  def create
    @sound_design = SoundDesign.new(sound_design_params)

    @sound_design.save
    redirect_to @sound_design
  end

  def show
    @sound_design = SoundDesign.find(params[:id])
  end

  def edit
    @sound_design = SoundDesign.find(params[:id])
  end

  def update
    @sound_design = SoundDesign.find(params[:id])

    if @sound_design.update(sound_design_params)
      redirect_to @sound_design
    else
      render 'edit'
    end
  end

  def destroy
    @sound_design = SoundDesign.find(params[:id])
    @sound_design.destroy

    redirect_to sound_designs_path
  end

  private
    def sound_design_params
      params.require(:sound_design).permit(:title, :description, :image, vimeos_attributes: [:id, :vimeo_url, :_destroy])
    end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @studios = Studio.all.order("created_at DESC")
  end

  def new
    @studio = Studio.new
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.save
    redirect_to studios_path
  end

  def edit
    @studio = Studio.find(params[:id])
  end

  def update
    @studio = Studio.find(params[:id])
    if @studio.update(studio_params)
      redirect_to studios_path
    else
      render 'edit'
    end
  end

  private
    def studio_params
      params.require(:studio).permit(:main_description, :image)
    end
end

app/controllers/vimeo_controller.rb
class VimeoController < ApplicationController
  def index
    @vimeos = Vimeo.all.order("created_at DESC")
  end

  def show
    @vimeo = Vimeo.find(params[:id])
  end

  def new
    @vimeo = Vimeo.new
  end

  def edit
    @vimeo = Vimeo.find(params[:id])
  end

  def create
    @vimeo = Vimeo.new(vimeo_params)

    @vimeo.save
    redirect_to @vimeo
  end

  def update
    @vimeo =Vimeo.find(params[:id])

    if @vimeo.update(vimeo_params)
      redirect_to @vimeo
    else
      render 'edit'
    end
  end

  def destroy
    @vimeo = Vimeo.find(params[:id])
    @vimeo.destroy
  end

  private
    def vimeo_params
      params.require(:vimeo).permit(:vimeo_url, :sound_design_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  
end

app/helpers/iframe_helper.rb
module IframeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def link_to_add_fields(name, f, association)
    ## create a new object from the association (:product_variants)
    new_object = f.object.send(association).klass.new

    ## just create or take the id from the new created object
    id = new_object.object_id

    ## create the fields form
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    ## pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})

  end
end

app/helpers/sound_design_helper.rb
module SoundDesignHelper
  def link_to_add_fields(name, f, association)
    ## create a new object from the association (:product_variants)
    new_object = f.object.send(association).klass.new

    ## just create or take the id from the new created object
    id = new_object.object_id

    ## create the fields form
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    ## pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/vimeo_helper.rb
module VimeoHelper
end

app/views/sound_designs/_form.html.erb
<div class="new-form-wrap">  
  <%= form_for @sound_design do |f| %>
    
    <% if @sound_design.errors.any? %>
      <div>
        <h2><%= pluralize(@sound_design.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @sound_design.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="back-wrap">
      <%= f.label :title, :class => "back-label" %>
      <%= f.text_field :title, :class => "back-field", :id => "title-back-field" %>
    </div>

    <div class="back-wrap">
      <%= f.label :description, :class => "back-label" %>
      <%= f.rich_text_area :description, :class => "back-field", :id => "description-back-field" %>
    </div>

    <div class="back-wrap">
      <% if @sound_design.image.attached? %>
        <%= image_tag @sound_design.image, style: "width: 200px; display: block" %>
      <% end %>
      <%= f.label :image, :class => "back-label" %><br>
      <%= f.file_field :image, direct_upload: true %>
    </div>

    <div class="back-wrap" id="iframe-wrap">
      <%= f.fields_for :vimeos do |f| %>
          <%= render 'vimeo_fields', f: f %>
      <% end %>
      <%= link_to_add_fields "Add another iframe", f, :vimeos %>
    </div>

    <div class="back-wrap" id="save-cancel-wrap">
      <%= f.submit "Save", :class => "create-btn" %>
  <% end %>
      <%= link_to 'Cancel', sound_designs_path, :class => "cancel-btn" %>
    </div>
</div>

<script>

  $('form').on('click', '.remove_fields', function(event) {
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('.vimeo_links').hide();
    return event.preventDefault();
  });

  $('form').on('click', '.add_fields', function(event) {
    console.log('clicked!')
      var regexp, time;
      time = new Date().getTime();
      regexp = new RegExp($(this).data('id'), 'g');
      $(this).before($(this).data('fields').replace(regexp, time));
      return event.preventDefault();
  });

</script>

app/views/sound_designs/_vimeo_fields.html.erb
<p class = "vimeo_links">
    <%= f.label :iframe_url, "Video iframe code: " %>
    <%= f.text_field :vimeo_url, :class => "back-field", :id => "iframe-back-field" %>
    <%= f.hidden_field :_destroy %>
    <%= link_to (fa_icon "times-circle"), '#', class: "remove_fields" %>
</p>

app/views/sound_designs/edit.html.erb
<h2 class="create-title">Edit sound design</h2>

<div class="create-body"><%= render 'form' %></div>

app/views/sound_designs/index.html.erb
<% if user_signed_in? %>
  <div class="add-wrapper"><%= link_to 'New Sound Design', sound_designs_new_path, :class => "add-button" %></div>
<% end %>

<div class="post-items-wrapper">
  <% @sound_designs.each do |sound_design| %>

    <div class="post-item-wrapper">
      <% if sound_design.image.attached? %>
        <div class="post-img"><%= link_to image_tag(url_for(sound_design.image), style: 'width: 89%'), sound_design %></div>
      <% end %>
      <h2 class="subtitle-box"><%= link_to sound_design.title, sound_design, :class => "subtitle" %></h2>
    </div>
  <% end %>
</div>

app/views/sound_designs/new.html.erb
<h2 class="create-title">Create a new sound design</h2>

<div class="create-body"><%= render 'form' %></div>

app/views/sound_designs/show.html.erb
<h1 class="title"><%= @sound_design.title %></h1>
<div class="description"><%= @sound_design.description %></div>

<div class="iframe-wrapper-advertising">
  <% @sound_design.vimeos.each do |vimeo| %>
    <div id="iframe-item-advertising">
      <%= vimeo.vimeo_url.html_safe %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <div class="command-wrapper">
    <%= link_to 'Back', sound_designs_path, :class => "button-item" %> 
    <%= link_to 'Edit', sound_design_edit_path, :class => "button-item" %>
    <%= link_to 'Delete', sound_design_path, :class => "button-item", :id => "button-item-delete", method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>
<% end %>

<div class="prev-next-wrapper">
  <div class="prev">
    <% if @sound_design.previous %>
      <%= link_to @sound_design.previous, :class => "pn-link-left", :action => 'go' do %>
        <div class="arrow-left"><i class="fas fa-chevron-left"></i></div>
        <div class="left-title"><%= @sound_design.previous.title %></div>
      <% end %>
    <% end %>
  </div>
  
  <div class="next">
    <% if @sound_design.next %>
      <%= link_to @sound_design.next, :class => "pn-link-right", :action => 'go' do %>
        <div class="arrow-right"><%= @sound_design.next.title %></div>
        <div class="right-title"><i class="fas fa-chevron-right"></i></div>
      <% end %>
    <% end %>
  </div>
</div>