config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources :homes
  resources :studios, only: [:index, :new, :create, :edit, :update]
  resources :songs
 
  get '/sound-designs' => 'sound_designs#index'
  get '/sound-designs/new' => 'sound_designs#new'
  post '/sound-designs' => 'sound_designs#create'
  get '/sound-designs/:id' => 'sound_designs#show', as: 'sound_design'
  get '/sound-designs/:id/edit' => 'sound_designs#edit', as: 'sound_design_edit'
  patch '/sound-designs/:id' => 'sound_designs#update'
  put '/sound-designs/:id' => 'sound_designs#update'
  delete '/sound-designs/:id' => 'sound_designs#destroy'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
  has_rich_text :main_description
  has_rich_text :sub_description
  has_one_attached :image
end

app/models/iframe.rb
class Iframe < ApplicationRecord
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  validates :title, presence: true,
                    length: { minimum: 2 }
  def previous
    Song.where(["id < ?", id]).last
  end

  def next
    Song.where(["id > ?", id]).first
  end

  has_many :iframes, dependent: :destroy

  accepts_nested_attributes_for :iframes, reject_if: :all_blank, allow_destroy: true
end

app/models/sound_design.rb
class SoundDesign < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  validates :title, presence: true,
                    length: { minimum: 2 }

  def previous
    SoundDesign.where(['id < ?', id]).last
  end

  def next
    SoundDesign.where(['id > ?', id]).first
  end

  has_many :vimeos, dependent: :destroy

  accepts_nested_attributes_for :vimeos, reject_if: :all_blank, allow_destroy: true
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_rich_text :main_description
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/vimeo.rb
class Vimeo < ApplicationRecord
  belongs_to :sound_design
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      NotifierMailer.notify_user(@contact).deliver
      redirect_to root_path, notice: "Message sent! Thank you for contacting us."
    else
      render :new, alert: "Cannot send message"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :last_name, :subject, :message, :email)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @homes = Home.all.order("created_at DESC")
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    @home.save
    redirect_to root_path
  end

  def show
    @home = Home.find(params[:id])
  end

  def edit
    @home = Home.find(params[:id])
  end

  def update
    @home = Home.find(params[:id])

    if @home.update(home_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
    def home_params
      params.require(:home).permit(:main_description, :sub_description, :image)
    end
end

app/controllers/iframe_controller.rb
class IframeController < ApplicationController
  def index
    
  end

  def show
    
  end

  def new
    
  end

  def edit
    
  end

  def create
    
  end

  def update
    
  end

  def destroy
    
  end

  private
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @songs = Song.all.order("created_at DESC")
  end
  
  def new
    @song = Song.new
    @song.iframes.build
  end

  def create
    @song = Song.new(song_params)

    @song.save
    redirect_to @song
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path
  end

  private
    def song_params
      params.require(:song).permit(:title, :description, :youtube_url, :soundcloud_url, :album_url, :image, iframes_attributes: [:id, :iframe_url, :_destroy])
    end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @studios = Studio.all.order("created_at DESC")
  end

  def new
    @studio = Studio.new
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.save
    redirect_to studios_path
  end

  def edit
    @studio = Studio.find(params[:id])
  end

  def update
    @studio = Studio.find(params[:id])
    if @studio.update(studio_params)
      redirect_to studios_path
    else
      render 'edit'
    end
  end

  private
    def studio_params
      params.require(:studio).permit(:main_description, :image)
    end
end

app/controllers/vimeo_controller.rb
class VimeoController < ApplicationController
  def index
    @vimeos = Vimeo.all.order("created_at DESC")
  end

  def show
    @vimeo = Vimeo.find(params[:id])
  end

  def new
    @vimeo = Vimeo.new
  end

  def edit
    @vimeo = Vimeo.find(params[:id])
  end

  def create
    @vimeo = Vimeo.new(vimeo_params)

    @vimeo.save
    redirect_to @vimeo
  end

  def update
    @vimeo =Vimeo.find(params[:id])

    if @vimeo.update(vimeo_params)
      redirect_to @vimeo
    else
      render 'edit'
    end
  end

  def destroy
    @vimeo = Vimeo.find(params[:id])
    @vimeo.destroy
  end

  private
    def vimeo_params
      params.require(:vimeo).permit(:vimeo_url, :sound_design_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  
end

app/helpers/iframe_helper.rb
module IframeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def link_to_add_fields(name, f, association)
    ## create a new object from the association (:product_variants)
    new_object = f.object.send(association).klass.new

    ## just create or take the id from the new created object
    id = new_object.object_id

    ## create the fields form
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    ## pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})

  end
end

app/helpers/sound_design_helper.rb
module SoundDesignHelper
  def link_to_add_fields(name, f, association)
    ## create a new object from the association (:product_variants)
    new_object = f.object.send(association).klass.new

    ## just create or take the id from the new created object
    id = new_object.object_id

    ## create the fields form
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    ## pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/vimeo_helper.rb
module VimeoHelper
end

app/views/contacts/new.html.erb
<div class="new-form">
    <div class="contact-details">
        <!--
        <div class="expertise-detail">
            <h4>Areas of Expertise</h4>
            <h1>Music Production</h1>
            <h1>Post Sound Production</h1>
            <h1>Sound Design</h1>
            <h1>Mixing / Mastering</h1>
        </div>
        -->
        <div class="email-detail">
            <h5>EMAIL</h5>
            <p>jeff@labelaurore.fr</p>
        </div>
        <div class="phone-detail">
            <h5>PHONE</h5>
            <p>+33 (0)6 29 47 95 03</p>
            <p>+44 (0)7 541 648 359</p>
        </div>
    </div>
    <div class="contact-form">
        <%= form_for @contact do |f| %>
            <% if flash[:error].present? %>
                <p>flash[:error]</p>
            <% end %>
            <h5 class="contact-item-title">GET IN TOUCH</h4>
            <div class="contact-item-wrap">
                <div class="contact-item-name-left">
                    <%= f.label :name, 'Name *', :class => 'label-item' %>
                    <%= f.text_field :name, required: true, :class =>'text-item-left' %>
                </div>
                <div class="contact-item-name-right">
                    <%= f.label :last_name, :class => 'label-item' %>
                    <%= f.text_field :last_name, :class =>'text-item-right' %>
                </div>
            </div>
            <p class="contact-item">
                <%= f.label :email, 'Email Adresse *', :class => 'label-item' %>
                <%= f.text_field :email, required: true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', :class =>'text-item' %>
            </p>
            <p class="contact-item">
                <%= f.label :subject, 'Subject *', :class => 'label-item' %>
                <%= f.text_field :subject, required: true, :class =>'text-item' %>
            </p>
            <p class="message-item">
                <%= f.label :message, 'Message *', :class => 'label-item' %>
                <%= f.text_area :message, as: :text, :class => 'text-message-item' %>
            </p>
            <div class= "hidden">
                <%= f.label :nickname %>
                <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
            </div>
            <p class="submit-item">
                <%= f.submit "Let's Work Together", :class => 'submit-button' %>
            </p>
        <% end %>
    </div>
</div>

app/views/homes/_form.html.erb
<div class="new-form-wrap">
  <%= form_for @home do |f| %>

    <!-- begin -->
    <% if @home.errors.any? %>
      <div>
        <h2><%= pluralize(@home.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @home.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <!-- end -->

    <!-- first paragraphe -->
    <div class="back-wrap">
      <%= f.label :main_description, :class => "back-label" %>
      <%= f.rich_text_area :main_description, :class => "back-field", :id => "main-description-back-field" %>
    </div>
    <!-- end -->

    <!-- image area -->
    <div class="back-wrap">
      <% if @home.image.attached? %>
        <%= image_tag @home.image, style: "width: 200px; display: block" %>
      <% end %>
      <%= f.label :image, :class => "back-label" %>
      <%= f.file_field :image, direct_upload: true %>
    </div>
    <!-- end -->

    <!-- second paragraphe -->
    <div class="back-wrap">
      <%= f.label :sub_description, :class => "back-label" %>
      <%= f.rich_text_area :sub_description, :class => "back-field", :id => "sub-description-back-field" %>
    </div>
    <!-- end -->

    <!-- buttons wrap -->
    <div class="back-wrap" id="save-cancel-wrap">
      <%= f.submit "Save", :class => "create-btn" %>
  <% end %>
      <%= link_to 'Cancel', root_path, :class => "cancel-btn" %>
    </div>
    <!-- end -->
</div>

app/views/homes/edit.html.erb
<h1 class="title">Edit Home</h1>
<div class="create-body"><%= render 'form' %></div>

app/views/homes/index.html.erb
<div class="index_home_studio">
  <h1 class="title">L'AURORE</h1>
  <div class="small_description">
    <%= @homes.first.main_description %>
  </div>

  <% if @homes.first.image.attached? %>
    <%= image_tag url_for(@homes.first.image), :class => "main_index_image" %>
  <% end %>

  <div class="sub_description_wrap">
    <%= @homes.first.sub_description %>
  </div>
  <% if user_signed_in? %>
    <div class="command-wrapper">
      <%= link_to "Edit", edit_home_path(1), :class => "button-item" %>
    </div>
  <% end %>
</div>

app/views/homes/new.html.erb
<h1 class="title">New Home</h1>
<div class="create-body"><%= render 'form' %></div>

app/views/songs/_form.html.erb
<div class="new-form-wrap">
  <%= form_for @song do |f| %>

    <% if @song.errors.any? %>
      <div>
        <h2><%= pluralize(@song.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @song.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="back-wrap">
      <%= f.label :title, :class => "back-label" %>
      <%= f.text_field :title, :class => "back-field", :id => "title-back-field" %>
    </div>

    <div class="back-wrap">
      <%= f.label :description, :class => "back-label" %>
      <%= f.rich_text_area :description, :class => "back-field", :id => "description-back-field" %>
    </div>

    <div class="back-wrap">
      <% if @song.image.attached? %>
        <%= image_tag @song.image, style: "width: 200px; display: block" %>
      <% end %>
      <%= f.label :image, :class => "back-label" %>
      <%= f.file_field :image, direct_upload: true %>
    </div>

    <div class="back-wrap" id="iframe-wrap">
      <%= f.fields_for :iframes do |f| %>
          <%= render 'iframe_fields', f: f %>
      <% end %>
      <%= link_to_add_fields "Add another iframe", f, :iframes %>
    </div>

    <div class="back-wrap" id="save-cancel-wrap">
      <%= f.submit "Save", :class => "create-btn" %>
  <% end %>
      <%= link_to 'Cancel', songs_path, :class => "cancel-btn" %>
    </div>
</div>

<script>

  $('form').on('click', '.remove_fields', function(event) {
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('.iframe_links').hide();
    return event.preventDefault();
  });

  $('form').on('click', '.add_fields', function(event) {
    console.log('clicked!')
      var regexp, time;
      time = new Date().getTime();
      regexp = new RegExp($(this).data('id'), 'g');
      $(this).before($(this).data('fields').replace(regexp, time));
      return event.preventDefault();
  });

</script>

app/views/songs/_iframe_fields.html.erb
<p class="iframe_links">
  <%= f.label :iframe_url, "Video iframe code: " %>
  <%= f.text_field :iframe_url, :class => "back-field", :id => "iframe-back-field" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to (fa_icon "times-circle"), '#', class: "remove_fields" %>
</p>

app/views/songs/edit.html.erb
<h2 class="create-title">Edit music production</h2>

<div class="create-body"><%= render 'form' %></div>

app/views/songs/index.html.erb
<% if user_signed_in? %>
  <div class="add-wrapper"><%= link_to "New Music Production", new_song_path, :class => "add-button" %></div>
<% end %>
<div class="post-items-wrapper">
  <% @songs.each do |song| %>

  <div class="post-item-wrapper">
    <% if song.image.attached? %>
      <div class="post-img"><%=link_to image_tag(url_for(song.image), style: 'width: 89%'), song %></div>
    <% end %>
    <h2 class="subtitle-box"><%= link_to song.title, song, :class => "subtitle" %></h2>
  </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<h2 class="create-title">Create a new music production</h2>

<div class="create-body"><%= render 'form' %></div>

app/views/songs/show.html.erb
<h1 class="title"><%= @song.title %></h1>

<div class="description">
  <%= @song.description %>
</div>

<div class="iframe-wrapper">
  <% @song.iframes.each do |iframe| %>
    <div id="iframe-item">
      <%= iframe.iframe_url.html_safe %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <div class="command-wrapper">
    <%= link_to "Back", songs_path, :class => "button-item" %>
    <%= link_to "Edit", edit_song_path, :class => "button-item" %>
    <%= link_to "Delete", song_path, :class => "button-item", :id => "button-item-delete", method: :delete, data: { confirm: "Are you sure?"} %>  
  </div>
<% end %>

<div class="prev-next-wrapper">
  <div class="prev">
    <% if @song.previous %>
      <%= link_to @song.previous, :class => "pn-link-left", :action => 'go' do %>
        <div class="arrow-left"><i class="fas fa-chevron-left"></i></div>
        <div class="left-title"><%= @song.previous.title %></div>
      <% end %>
    <% end %>
  </div>
  
  <div class="next">
    <% if @song.next %>
      <%= link_to @song.next, :class => "pn-link-right", :action => 'go' do %>
        <div class="arrow-right"><%= @song.next.title %></div>
        <div class="right-title"><i class="fas fa-chevron-right"></i></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/studios/_form.html.erb
<div class="new-form-wrap">
  <%= form_for @studio do |f| %>
    <!-- begin -->
    <% if @studio.errors.any? %>
      <div>
        <h2><%= pluralize(@studio.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @studio.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <!-- end -->
    <!-- main description -->
    <div class="back-wrap">
      <%= f.label :main_description, :class => "back-label" %>
      <%= f.rich_text_area :main_description, :class => "back-field", :id => "main-description-back-field" %>
    </div>
    <!-- end -->
    <!-- image wrap -->
    <div class="back-wrap">
      <% if @studio.image.attached? %>
        <%= image_tag @studio.image, style: "width: 200px; display: block" %>
      <% end %>
      <%= f.label :image, :class => "back-label" %>
      <%= f.file_field :image, direct_upload: true %>
    </div>
    <!-- end -->
    <!-- buttons wrap -->
    <div class="back-wrap" id="save-cancel-wrap">
      <%= f.submit "Save", :class => "create-btn" %>
  <% end %>
      <%= link_to 'Cancel', studios_path, :class => "cancel-btn" %>
    </div>
    <!-- end -->
</div>

app/views/studios/edit.html.erb
<h1 class="title">Edit Studio</h1>
<div class="create-body"><%= render 'form' %></div>

app/views/studios/index.html.erb
<div class="index_home_studio">
  <h1 class="title">Studio L'Aurore</h1>
  <div class="small_description">
    <%= @studios.first.main_description %>
  </div>
  <% if @studios.first.image.attached? %>
    <%= image_tag url_for(@studios.first.image), :class => "main_index_image" %>
  <% end %>

  <% if user_signed_in? %>
    <div class="command-wrapper">
      <%= link_to "Edit", edit_studio_path(1), :class => "button-item" %>
    </div>
  <% end %>
</div>

app/views/studios/new.html.erb
<h1 class="title">New Studio</h1>
<div class="create-body"><%= render 'form' %></div>