config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources :homes
  resources :studios, only: [:index, :new, :create, :edit, :update]
  resources :songs
 
  get '/sound-designs' => 'sound_designs#index'
  get '/sound-designs/new' => 'sound_designs#new'
  post '/sound-designs' => 'sound_designs#create'
  get '/sound-designs/:id' => 'sound_designs#show', as: 'sound_design'
  get '/sound-designs/:id/edit' => 'sound_designs#edit', as: 'sound_design_edit'
  patch '/sound-designs/:id' => 'sound_designs#update'
  put '/sound-designs/:id' => 'sound_designs#update'
  delete '/sound-designs/:id' => 'sound_designs#destroy'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
  has_rich_text :main_description
  has_rich_text :sub_description
  has_one_attached :image
end

app/models/iframe.rb
class Iframe < ApplicationRecord
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  validates :title, presence: true,
                    length: { minimum: 2 }
  def previous
    Song.where(["id < ?", id]).last
  end

  def next
    Song.where(["id > ?", id]).first
  end

  has_many :iframes, dependent: :destroy

  accepts_nested_attributes_for :iframes, reject_if: :all_blank, allow_destroy: true
end

app/models/sound_design.rb
class SoundDesign < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  validates :title, presence: true,
                    length: { minimum: 2 }

  def previous
    SoundDesign.where(['id < ?', id]).last
  end

  def next
    SoundDesign.where(['id > ?', id]).first
  end

  has_many :vimeos, dependent: :destroy

  accepts_nested_attributes_for :vimeos, reject_if: :all_blank, allow_destroy: true
end

app/models/studio.rb
class Studio < ApplicationRecord
  has_rich_text :main_description
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/vimeo.rb
class Vimeo < ApplicationRecord
  belongs_to :sound_design
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @homes = Home.all.order("created_at DESC")
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    @home.save
    redirect_to root_path
  end

  def show
    @home = Home.find(params[:id])
  end

  def edit
    @home = Home.find(params[:id])
  end

  def update
    @home = Home.find(params[:id])

    if @home.update(home_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
    def home_params
      params.require(:home).permit(:main_description, :sub_description, :image)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @songs = Song.all.order("created_at DESC")
  end
  
  def new
    @song = Song.new
    @song.iframes.build
  end

  def create
    @song = Song.new(song_params)

    @song.save
    redirect_to @song
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render 'edit'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path
  end

  private
    def song_params
      params.require(:song).permit(:title, :description, :youtube_url, :soundcloud_url, :album_url, :image, iframes_attributes: [:id, :iframe_url, :_destroy])
    end
end

app/controllers/vimeo_controller.rb
class VimeoController < ApplicationController
  def index
    @vimeos = Vimeo.all.order("created_at DESC")
  end

  def show
    @vimeo = Vimeo.find(params[:id])
  end

  def new
    @vimeo = Vimeo.new
  end

  def edit
    @vimeo = Vimeo.find(params[:id])
  end

  def create
    @vimeo = Vimeo.new(vimeo_params)

    @vimeo.save
    redirect_to @vimeo
  end

  def update
    @vimeo =Vimeo.find(params[:id])

    if @vimeo.update(vimeo_params)
      redirect_to @vimeo
    else
      render 'edit'
    end
  end

  def destroy
    @vimeo = Vimeo.find(params[:id])
    @vimeo.destroy
  end

  private
    def vimeo_params
      params.require(:vimeo).permit(:vimeo_url, :sound_design_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  
end

app/helpers/iframe_helper.rb
module IframeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def link_to_add_fields(name, f, association)
    ## create a new object from the association (:product_variants)
    new_object = f.object.send(association).klass.new

    ## just create or take the id from the new created object
    id = new_object.object_id

    ## create the fields form
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    ## pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})

  end
end

app/helpers/sound_design_helper.rb
module SoundDesignHelper
  def link_to_add_fields(name, f, association)
    ## create a new object from the association (:product_variants)
    new_object = f.object.send(association).klass.new

    ## just create or take the id from the new created object
    id = new_object.object_id

    ## create the fields form
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    ## pass down the link to the fields form
    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/vimeo_helper.rb
module VimeoHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L'Aurore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Display:wght@300;400;500;600;700;800&family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/65fb5af6ee.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="header">
      <div class="logo-box">
          <%= link_to image_tag("laurore.jpg", :class => "style_logo"), root_path, active: :exact %>
      </div>

      <!-- If you need to inclue the link_to into a div 
      https://stackoverflow.com/questions/30639767/how-can-we-add-link-to-with-a-div-in-rails 
      -->

      <!-- Alert messages -->


      <div class="navbar">
        <div class="nav-link">
          <%= active_link_to "L'Aurore", root_path, active: :exact, :class => "menu_button" %>
        </div>
        <div class="nav-link">
          <%= active_link_to "Music Production", songs_path, :class => "menu_button" %>
        </div>
        <div class="nav-link">
          <%= active_link_to "Music / Sound Design for Advertising", sound_designs_path, :class => "menu_button" %>
        </div>
        <div class="nav-link">
          <%= active_link_to "Studio", studios_path, :class => "menu_button" %>
        </div>
        <div class="nav-link" id="last-nav-link">
          <%= active_link_to "Contact", new_contact_path, :class => "menu_button" %>
        </div>
      </div>

      <div class="social">
        <a href="https://www.facebook.com/AuLabelAurore"  target="_blank" class="social_icons"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/label.aurore/" target="_blank" class="social_icons"><i class="fab fa-instagram"></i></a>
        <a href="https://vimeo.com/user98874758" target="_blank" class="social_icons"><i class="fab fa-vimeo-v"></i></a>
      </div>
      <div id="hamburger">
        <button id="hamburger-button"><ion-icon name="menu-outline"></ion-icon></button>

        <div id="hamburger-sidebar">
          <div id="hamburger-sidebar-header">
            <div class="logo-box-burger">
              <%= link_to image_tag("laurore.jpg", :class => "style-logo-burger"), root_path, active: :exact %>
            </div>
            <button id="hamburger-button-closed"><ion-icon name="close-outline" id="closed-burger"></ion-icon></button>
          </div>

          <div id="hamburger-sidebar-body">
            <div class="nav-link-burger">
              <%= link_to "L'Aurore", root_path, :class => "burger_button" %>
            </div>
            <div class="nav-link-burger">
              <%= link_to "Music Production", songs_path, :class => "burger_button" %>
            </div>
            <div class="nav-link-burger">
              <%= link_to "Music / Sound Design for Advertising", sound_designs_path, :class => "burger_button" %>
            </div>
            <div class="nav-link-burger">
              <%= link_to "Studio", studios_path, :class => "burger_button" %>
            </div>
            <div class="nav-link-burger" id="last-nav-link-burger">
              <%= link_to "Contact", new_contact_path, :class => "burger_button" %>
            </div>
            <div class="social-footer-burger">
              <a href="https://www.facebook.com/AuLabelAurore"  target="_blank" class="social_icons_footer"><i class="fab fa-facebook-f"></i></a>
              <a href="https://www.instagram.com/label.aurore/" target="_blank" class="social_icons_footer"><i class="fab fa-instagram"></i></a>
              <a href="https://vimeo.com/user98874758" target="_blank" class="social_icons_footer" id="social_icons_footer_right"><i class="fab fa-vimeo-v"></i></a>
            </div>
          </div>
        </div>
        <div id="hamburger-overlay"></div>
      </div>
    </div>

    <div class="flash-messages">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <div class="sign-out-wrap">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "sign-out-button" %>
      <% end %>
    </div>

    <%= yield %>

    <footer>
      <div class="social-footer">
        <a href="https://www.facebook.com/AuLabelAurore"  target="_blank" class="social_icons_footer"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/label.aurore/" target="_blank" class="social_icons_footer"><i class="fab fa-instagram"></i></a>
        <a href="https://vimeo.com/user98874758" target="_blank" class="social_icons_footer" id="social_icons_footer_right"><i class="fab fa-vimeo-v"></i></a>
      </div>
      <div class="made-by">
        <a href="https://github.com/mantecajc" target="_blank" class="made_by">Made by mantecajc</a>
      </div>
    </footer>
  </body>
  <%= javascript_pack_tag 'hamburger' %>
</html>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>